# Default values for policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingressHostnamePattern: s??????.sandbox.crownlabs.polito.it

namespaceSelector:
  matchExpressions:
    - key: crownlabs.polito.it/type
      operator: In
      values:
      - sandbox
