---
- hosts: all
  become: yes

  roles:
  - role: ../roles/gather-desktop-environment-facts
  - role: ../roles/ubuntu-pre
  - role: ../roles/crownlabs
    when: crownlabs_mode
  - role: ../roles/wireshark
  - role: ../roles/docker
  - role: ../roles/gns3
  - role: ../roles/netlab-generic
  - role: ../roles/ubuntu-post
