---
- hosts: all
  become: yes

  roles:
  - role: ../roles/gather-desktop-environment-facts
  - role: ../roles/ubuntu-pre
  - role: ../roles/crownlabs
    when: crownlabs_mode
  - role: ../roles/codeblocks
  - role: ../roles/pycharm
  - role: ../roles/ttpu-os
  - role: ../roles/ubuntu-post
