---
# tasks file for wireshark

- name: Assert that a Desktop Environment is installed
  fail:
    msg: "You are attempting to install 'Wireshark', but no Desktop Environment seems to be available"
  when: not desktop_environment_detected

- name: Let non root to capture traffic
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'

- name: Install the Wireshark package
  apt:
    name: "wireshark"
    state: present

- name: Add the local user to the wireshark group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: wireshark
