apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: harbor-database
  namespace: harbor
spec:
  databases:
    registry: harbor
    notary_server: harbor 
    notary_signer: harbor 
  numberOfInstances: 3
  podAnnotations:
    backup.velero.io/backup-volumes: pgdata
  postgresql:
    version: "12"
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi
  teamId: harbor
  users:
    harbor:
    - superuser
    - createdb
  volume:
    size: 10Gi
    storageClass: rook-ceph-block
  affinity: {}
