---
# Install kubernetes (not configure the cluster)

- name: Create docker daemon directory
  file:
    path: /etc/docker
    state: directory

- name: Create docker daemon file
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: Restart the docker service

- name: Setup the kubernetes repository
  include: "{{ role_path }}/tasks/setup-kubernetes-repository.yaml"

- name: Install kubernetes
  apt:
    name: "{{ kubernetes_packages }}"
    state: present
  vars:
    kubernetes_packages:
    - "kubelet={{ k8s_version }}"
    - "kubeadm={{ k8s_version }}"
    - "kubectl={{ k8s_version }}"
  notify: Hold the kubernetes version

# Pre-fetch docker images in order to reduce the pressure on the network
# (and avoiding to download all images) when students are asked to install k8s in their VM
- name: pull kubernetes image
  command: kubeadm config images pull

- name: Turn swap off (1/2)
  command: swapoff -a

- name: Disable swap (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Bridged iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
