---
# tasks file for polycube

- name: Install polycube pre-requisites
  apt:
    name: git
    state: present

- name: Set the polycube parameters
  set_fact:
    polycube_src: "/tmp/polycube"
    polycube_version: release/v0.11.0

- name: Checkout the polycube repository
  git:
    repo: "https://github.com/polycube-network/polycube"
    dest: "{{ polycube_src }}"
    version: "{{ polycube_version }}"
    recursive: yes
    depth: 1
  become: no

- name: Install polycube
  command:
    cmd: ./scripts/install.sh
    chdir: "{{ polycube_src }}"
    creates: /usr/local/bin/polycubectl
  become: no


- name: Install hping3p dependencies
  apt:
    name: "{{ hping3p_dependencies }}"
    state: present
  vars:
    hping3p_dependencies:
    - libpcap-dev
    - tcl
    - tcl-dev

- name: Set hping3p directories
  set_fact:
    hping3p_base: "/tmp/hping3p"

- name: Checkout the hping3p repository
  git:
    repo: "https://github.com/francescoraves483/hping.git"
    dest: "{{ hping3p_base }}"
  become: no

- name: Ensure man8 directory exists
  file:
    path: "/usr/local/man/man8"
    state: directory

- name: Link net/bpf.h -> pcap-bpf.h
  file:
    src: "/usr/include/pcap-bpf.h"
    dest: "/usr/include/net/bpf.h"
    state: link

- name: Configure hping3p
  command:
    chdir: "{{ hping3p_base }}"
    cmd: ./configure
  become: no

- name: Make hping3p
  make:
    chdir: "{{ hping3p_base }}"
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"
  become: no

- name: Install hping3p
  make:
    chdir: "{{ hping3p_base }}"
    target: forced-install


- name: Install utility tools
  apt:
    name: "{{ to_install }}"
    state: present
  vars:
    to_install:
    - ncat
    - net-tools
