name: 'retrieve-build-matrix'
description: 'Reads the build matrix specification from a json file and returns it formatted and filtered as requested'
inputs:
  path:
    description: 'The path of the json file containing the matrix configuration.'
    required: true
  filterOptional:
    description: 'Whether to filter optional entries.'
    required: false
    default: "false"
outputs:
  matrix:
    description: 'The resulting build matrix specification.'
runs:
  using: 'node16'
  main: 'dist/index.js'
