---
- name: Install ansible
  apt:
    name: ansible
    state: latest

- name: Setup the kubernetes repository
  include: "{{ role_path }}/../kubernetes/tasks/setup-kubernetes-repository.yaml"

- name: Install kubectl
  apt:
    name: "kubectl={{ k8s_version }}"
    state: present

- name: Install virt-manager
  apt:
    name: virt-manager
    state: latest

# Allow typing the password when using virt-manager to connect to the remote server
- name: Install ssh-askpass
  apt:
    name: ssh-askpass
    state: latest
