apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ include "policies.fullname" . }}-disallow-empty-ingress-host
  labels:
    {{- include "policies.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Disallow empty Ingress host
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
        An ingress resource needs to define an actual host name
        in order to be valid. This policy ensures that there is a
        hostname for each rule defined.      
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: disallow-empty-ingress-host
      match:
        resources:
          kinds:
            - Ingress
        {{- with .Values.namespaceSelector }}
          namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      validate:
        message: "The Ingress host name must be defined, not empty."
        deny:
          conditions:
            - key: "{{printf "{{request.object.spec.rules[].host || `[]` | length(@) }}"}}"
              operator: NotEquals
              value: "{{printf "{{ request.object.spec.rules[].http || `[]` | length(@) }}"}}"
