apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ include "policies.fullname" . }}-restrict-host-ingress
  labels:
    {{- include "policies.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Restrict Ingress hostname
    policies.kyverno.io/category: Security
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/description: >-
        An ingress resource needs to define a valid hostname. 
        This policy ensures that the hostname follows the form {{ .Values.host }}.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: restrict-ingress-hostnames
    match:
      resources:
        kinds:
        - Ingress
      {{- with .Values.namespaceSelector }}
        namespaceSelector:
          {{- toYaml . | nindent 10 }}
      {{- end }}
    validate:
      message: "The host name must be in the form {{ .Values.ingressHostnamePattern }}." 
      pattern:
        spec:
          rules:
          - host: {{ .Values.ingressHostnamePattern }}
