# This rule is not used by the project testcrownlabs itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the crownlabs.polito.it.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testcrownlabs
    app.kubernetes.io/managed-by: kustomize
  name: template-editor-role
rules:
- apiGroups:
  - crownlabs.polito.it
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crownlabs.polito.it
  resources:
  - templates/status
  verbs:
  - get
