---
# tasks file for ubuntu-post

- name: Install utility tools
  apt:
    name: "{{ to_install }}"
    state: present
  vars:
    to_install:
    - curl
    - htop
    - iftop
    - iotop
    - nano
    - vim

- name: Install zerofree
  apt:
    name: zerofree
    state: present
  when: not crownlabs_mode

- name: Clean apt cache
  command: apt clean

- name: Gather journal files information
  find:
    paths: "/var/log/journal"
    file_type: directory
  register: journal_directories

- name: Remove all journal files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: >
    {{ journal_directories.files }}

- name: Allow automatic login
  template:
    src: templates/lightdm.conf
    dest: /etc/lightdm/lightdm.conf.d/10-autologin.conf
    owner: root
    group: root
    mode: '0644'
  when: desktop_environment_detected and xfce_detected and not crownlabs_mode

- name: Disable the screensaver and the lock screen
  xfconf:
    channel: xfce4-screensaver
    property: "{{ item }}"
    value_type: "bool"
    value: "false"
  with_items:
  - /saver/enabled
  - /lock/enabled
  become: true
  become_user: "{{ ansible_user }}"
  when: desktop_environment_detected and xfce_detected

- name: Disable compositing (i.e. shadows) in xfce
  xfconf:
    channel: xfwm4
    property: /general/use_compositing
    value_type: "bool"
    value: "false"
  become: true
  become_user: "{{ ansible_user }}"
  when: desktop_environment_detected and xfce_detected

- name: Copy the README file
  copy:
    src: files/README
    dest: /home/{{ ansible_user }}/Desktop
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: not crownlabs_mode

- name: Copy the zerohdd script to the root folder
  copy:
    src: files/zerohdd.sh
    dest: /root
    owner: root
    group: root
    mode: '0644'
  when: not crownlabs_mode
