---
- name: Restart the docker service
  systemd:
    name: docker
    state: restarted

- name: Hold the kubernetes version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "kubelet"
    - "kubeadm"
    - "kubectl"
