apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: iscsi-rook-ceph
  namespace: iscsi-rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.4
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/iscsi-rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
  external:
    enable: false
  mgr:
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
  monitoring:
    enabled: true
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
    provider: ""
    selectors: null
  rbdMirroring:
    workers: 0
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    config: null
    nodes:
    - config: null
      devices:
      - config: null
        name: sda
      - config: null
        name: sdb
      - config: null
        name: sdc
      name: worker-1
      resources: {}
    - config: null
      devices:
      - config: null
        name: sda
      - config: null
        name: sdb
      - config: null
        name: sdc
      name: worker-2
      resources: {}
    - config: null
      devices:
      - config: null
        name: sda
      - config: null
        name: sdb
      - config: null
        name: sdc
      name: worker-3
      resources: {}
    - config: null
      devices:
      - config: null
        name: sda
      - config: null
        name: sdb
      - config: null
        name: sdc
      name: worker-4
      resources: {}
    storageClassDeviceSets: null
    useAllDevices: false
