---
# tasks file for gather-desktop-environment-facts

- name: Check whether a Desktop Environment is installed
  shell: command -v startx
  register: startx_presence_check
  changed_when: False
  failed_when: False
  when: install_desktop_environment is undefined or install_desktop_environment == "false"

- name: Check whether XFCE is installed
  shell: command -v startxfce4
  register: xfce_presence_check
  changed_when: False
  failed_when: False
  when: install_desktop_environment is undefined or install_desktop_environment == "false"

- name: Set facts
  set_fact:
    desktop_environment_detected: "{{ startx_presence_check.stdout != '' }}"
    xfce_detected: "{{ xfce_presence_check.stdout != '' }}"
  when: install_desktop_environment is undefined or install_desktop_environment == "false"

- name: Set facts
  set_fact:
    desktop_environment_detected: "{{ install_desktop_environment }}"
    xfce_detected: "{{ install_desktop_environment }}"
  when: install_desktop_environment is defined and install_desktop_environment == "true"

- name: Report whether a Desktop Environment has been detected
  debug:
    msg:
    - "Desktop Environment detected: {{ desktop_environment_detected }}"
    - "XFCE detected: {{ xfce_detected }}"
