apiVersion: v1
kind: Namespace
metadata:
  name: minio-s3
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-s3
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: s3
      protocol: TCP
      port: 9000
      targetPort: s3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio-s3
  labels:
    app.kubernetes.io/name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2021-06-14T01-29-23Z
        imagePullPolicy: IfNotPresent
        args: ["server", "/data"]
        env:
        - name: MINIO_ROOT_USER
          value: crownlabs_backup
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-passwd
              key: passwd
        volumeMounts:
        - mountPath: /data
          name: data
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 9000
          name: s3
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: s3
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: data
        iscsi:
          targetPortal: 1.2.3.4
          iqn: iqn.yyyymm.backward-naming-authority:unique-device-name
          lun: 1
          fsType: ext4
          readOnly: false
          chapAuthDiscovery: true
          chapAuthSession: true
          secretRef:
            name: minio-iscsi-chap-secret
---
apiVersion: v1
kind: Secret
metadata:
  namespace: minio-s3
  name: minio-passwd
  labels:
    app.kubernetes.io/name: minio
data:
# echo -n "password" | base64
  passwd: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  namespace: minio-s3
  name: minio-iscsi-chap-secret
  labels:
    app.kubernetes.io/name: minio
type: "kubernetes.io/iscsi-chap"
data:
# echo -n "username" | base64
  node.session.auth.username: dXNlcm5hbWU=
# echo -n "password" | base64
  node.session.auth.password: cGFzc3dvcmQ=
