apiVersion: v1
data:
  .env: |
    APP_DEBUG=false
    APP_BUGSNAG=true
    APP_URL=https://support.crownlabs.polito.it
    APP_KEY=base64:edcbeW2vK8rIuavnG7lF4OM1qAUfOoG6vin5ZucJUug=
    DB_TYPE=mysql
    DB_HOST="faveo-db-mysql-master"
    DB_PORT="3306"
    DB_DATABASE=<insert db name here>
    DB_USERNAME=<insert db username here>
    DB_PASSWORD=<insert db password here>
    ADMIN_USERNAME=<insert admin username here>
    ADMIN_PASSWORD=<insert admin password here>
    MAIL_DRIVER=smtp
    MAIL_HOST=mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    CACHE_DRIVER=file
    SESSION_DRIVER=file
    SESSION_COOKIE_NAME=faveo_4601
    QUEUE_DRIVER=sync
    JWT_TTL=4
    FCM_SERVER_KEY=AIzaSyCyx5OFnsRFUmDLTMbPV50ZMDUGSG-bLw4
    FCM_SENDER_ID=661051343223
    REDIS_DATABASE=0
    JWT_SECRET=<insert jwt secret here>
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: faveo
    app.kubernetes.io/part-of: faveo
  name: faveo-php-configmap
