apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: faveo-db
  namespace: crownlabs-ticketing
spec:
  replicas: 3
  secretName: faveo-db-auth
  volumeSpec:
    persistentVolumeClaim:
      storageClassName: "rook-ceph-block"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
  podSpec:
    annotations:
      backup.velero.io/backup-volumes: data
