---
- name: Install libvirt
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: false
  vars:
    packages:
    - bridge-utils
    - cloud-image-utils
    - cpu-checker
    - libguestfs-tools
    - libvirt-clients
    - libvirt-daemon-system
    - qemu-utils
    - qemu-kvm

- name: Install dnsmasq-base
  apt:
    name: dnsmasq-base
    state: latest
