---
# tasks for codeblocks
# adds the ppa repository, since the packets available in the default repositories of ubuntu < 20.04 are outdated
# original instructions here: http://ubuntuhandbook.org/index.php/2020/03/install-codeblocks-20-03-ubuntu-18-04/

- name: Assert that a Desktop Environment is installed
  fail:
    msg: "You are attempting to install 'CodeBlocks', but no Desktop Environment seems to be available"
  when: not desktop_environment_detected

- name: Install the build-essential tools
  apt:
    name: "build-essential"
    state: present

- name: Add codeblocks APT repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/codeblocks-devs/release/ubuntu {{ansible_distribution_release}} main
  when: ansible_distribution_major_version < '20'

- name: Install the codeblocks packages
  apt:
    name: "{{ to_install }}"
    state: present
  vars:
    to_install:
    - codeblocks
    - codeblocks-contrib

- name: Create the CodeBlocks desktop file
  copy:
    src: /usr/share/applications/codeblocks.desktop
    dest: /home/{{ ansible_user }}/Desktop
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
