---
# tasks file for pycharm

- name: Assert that a Desktop Environment is installed
  fail:
    msg: "You are attempting to install 'PyCharm', but no Desktop Environment seems to be available"
  when: not desktop_environment_detected

- name: Install Python 3 packages
  apt:
    name: "{{ python3_packages }}"
    state: present
  vars:
    python3_packages:
    - python3
    - python3-venv
    - python3-setuptools

- name: Set PyCharm variables
  set_fact:
    pycharm_version: "2021.2.1"
    pycharm_path: "/usr/share/pycharm"
    pycharm_desktop_file_path: "/usr/share/applications"

- name: Make sure the PyCharm directory exists
  file:
    path: "{{ pycharm_path }}"
    state: directory

- name: Install PyCharm
  unarchive:
    remote_src: yes
    src: https://download.jetbrains.com/python/pycharm-community-{{pycharm_version}}.tar.gz
    dest: "{{ pycharm_path }}"
    creates: "{{ pycharm_path }}/bin/pycharm.sh"
    owner: root
    group: root
    extra_opts:
    - --strip-components=1

- name: Add the PyCharm executable to the path
  file:
    src: "{{ pycharm_path }}/bin/pycharm.sh"
    dest: "/usr/local/bin/pycharm"
    state: link

- name: Install the PyCharm Desktop file
  template:
    src: templates/pycharm.desktop
    dest: "{{ pycharm_desktop_file_path }}/PyCharm.desktop"
