{{- if .Values.createClusterRoles -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crownlabs-view-workspaces
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crownlabs-view-workspaces
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crownlabs-view-image-lists
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crownlabs-view-image-lists
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
{{- end }}
